---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  DEVENV_DIR: "{{.PROJECT_DIR}}/devenv"

includes:
  check: .taskfiles/check.yaml
  pre-commit: .taskfiles/pre-commit.yaml

tasks:
  lint:
    desc: lint codebase
    dir: "{{.PROJECT_DIR}}"
    cmds:
      - task: pre-commit:init
      - task: pre-commit:run
